{
  "error": "General error processing with Ollama: 1 validation error for ExtendedInvoice\n  Invalid JSON: EOF while parsing a value at line 7655 column 0 [type=json_invalid, input_value='{\\n  \"type\": \"receipt_re...      \"quantity\": 50,\\n', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/json_invalid",
  "traceback": "Traceback (most recent call last):\n  File \"d:\\deymed\\invoces\\ollama_model_test.py\", line 85, in process_file\n    invoice = ExtendedInvoice.model_validate_json(generated_text)\n  File \"D:\\deymed\\invoces\\.venv\\Lib\\site-packages\\pydantic\\main.py\", line 744, in model_validate_json\n    return cls.__pydantic_validator__.validate_json(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        json_data, strict=strict, context=context, by_alias=by_alias, by_name=by_name\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\npydantic_core._pydantic_core.ValidationError: 1 validation error for ExtendedInvoice\n  Invalid JSON: EOF while parsing a value at line 7655 column 0 [type=json_invalid, input_value='{\\n  \"type\": \"receipt_re...      \"quantity\": 50,\\n', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/json_invalid\n",
  "time": 17236.061527490616
}